// <auto-generated />
using System;
using AcikVeriPortali.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcikVeriPortali.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcikVeriPortali.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#28a745",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3929),
                            Description = "Ekonomik veriler ve istatistikler",
                            IsActive = true,
                            Name = "Ekonomi",
                            UpdatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3929)
                        },
                        new
                        {
                            Id = 2,
                            Color = "#dc3545",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3932),
                            Description = "Sağlık verileri ve istatistikler",
                            IsActive = true,
                            Name = "Sağlık",
                            UpdatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3933)
                        },
                        new
                        {
                            Id = 3,
                            Color = "#007bff",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3934),
                            Description = "Eğitim verileri ve istatistikler",
                            IsActive = true,
                            Name = "Eğitim",
                            UpdatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3935)
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ffc107",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3936),
                            Description = "Ulaştırma verileri ve istatistikler",
                            IsActive = true,
                            Name = "Ulaştırma",
                            UpdatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3937)
                        },
                        new
                        {
                            Id = 5,
                            Color = "#20c997",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3939),
                            Description = "Çevre verileri ve istatistikler",
                            IsActive = true,
                            Name = "Çevre",
                            UpdatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3939)
                        });
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataQualityReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("CompletenessScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsistencyScore")
                        .HasColumnType("double precision");

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<int>("InvalidRecords")
                        .HasColumnType("integer");

                    b.Property<string>("Issues")
                        .HasColumnType("text");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TimelinessScore")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer");

                    b.Property<int>("ValidRecords")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("DataSetId");

                    b.HasIndex("Status");

                    b.ToTable("DataQualityReports");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("APIEndpoint")
                        .HasColumnType("text");

                    b.Property<string>("AccessLevel")
                        .HasColumnType("text");

                    b.Property<string>("Acknowledgments")
                        .HasColumnType("text");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("BackupLocation")
                        .HasColumnType("text");

                    b.Property<string>("BackupStatus")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("text");

                    b.Property<string>("Citation")
                        .HasColumnType("text");

                    b.Property<string>("ComplianceInfo")
                        .HasColumnType("text");

                    b.Property<string>("ConfidenceLevel")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("CoordinateSystem")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentVersion")
                        .HasColumnType("text");

                    b.Property<string>("DOI")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataCollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataCollectionMethod")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataCollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataDictionary")
                        .HasColumnType("text");

                    b.Property<string>("DataLanguage")
                        .HasColumnType("text");

                    b.Property<string>("DataLineage")
                        .HasColumnType("text");

                    b.Property<string>("DataQualityScore")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Disclaimers")
                        .HasColumnType("text");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalLinks")
                        .HasColumnType("text");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FundingSource")
                        .HasColumnType("text");

                    b.Property<string>("GeographicCoverage")
                        .HasColumnType("text");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMachineReadable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpenFormat")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastBackupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("License")
                        .HasColumnType("text");

                    b.Property<string>("Limitations")
                        .HasColumnType("text");

                    b.Property<string>("MarginOfError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviewData")
                        .HasColumnType("text");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedDataSets")
                        .HasColumnType("text");

                    b.Property<string>("ResponsiblePerson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RetentionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetentionPolicy")
                        .HasColumnType("text");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("SamplingMethod")
                        .HasColumnType("text");

                    b.Property<string>("SecurityClassification")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TechnicalSpecifications")
                        .HasColumnType("text");

                    b.Property<string>("TemporalCoverage")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdateFrequency")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UsageExamples")
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevel");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DOI")
                        .IsUnique();

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("DataSets");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetAccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<double>("ResponseTimeMs")
                        .HasColumnType("double precision");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserIp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccessType");

                    b.HasIndex("AccessedAt");

                    b.HasIndex("DataSetId");

                    b.HasIndex("UserId");

                    b.ToTable("DataSetAccessLogs");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DataSetId");

                    b.HasIndex("IsApproved");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("DataSetComments");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DownloadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserIp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId");

                    b.HasIndex("DownloadedAt");

                    b.HasIndex("UserId");

                    b.ToTable("DataSetDownloads");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetExport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Filters")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RequestedById")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedById");

                    b.HasIndex("Status");

                    b.ToTable("DataSetExports");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId", "Key")
                        .IsUnique();

                    b.ToTable("DataSetMetadata");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId", "ColumnName")
                        .IsUnique();

                    b.ToTable("DataSetSchemas");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<string>("TopCity")
                        .HasColumnType("text");

                    b.Property<string>("TopCountry")
                        .HasColumnType("text");

                    b.Property<string>("TopReferrer")
                        .HasColumnType("text");

                    b.Property<string>("TopUserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UniqueVisitors")
                        .HasColumnType("integer");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("DataSetId", "Date")
                        .IsUnique();

                    b.ToTable("DataSetStatistics");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DataSetId", "UserId")
                        .IsUnique();

                    b.ToTable("DataSetSubscriptions");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UsageCount");

                    b.ToTable("DataSetTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#17a2b8",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(4003),
                            Description = "Açık veri standartlarına uygun veriler",
                            Name = "Açık Veri",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#fd7e14",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(4005),
                            Description = "Gerçek zamanlı güncellenen veriler",
                            Name = "Gerçek Zamanlı",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#6f42c1",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(4007),
                            Description = "Coğrafi bilgi içeren veriler",
                            Name = "Coğrafi",
                            UsageCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#e83e8c",
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(4008),
                            Description = "İstatistiksel analiz verileri",
                            Name = "İstatistik",
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Changelog")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<string>("FileFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DataSetId", "Version")
                        .IsUnique();

                    b.ToTable("DataSetVersions");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataSetId")
                        .HasColumnType("integer");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId");

                    b.HasIndex("UserId");

                    b.HasIndex("ViewedAt");

                    b.ToTable("DataSetViews");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.PortalStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveDataSets")
                        .HasColumnType("integer");

                    b.Property<double>("AverageResponseTime")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<int>("NewDataSets")
                        .HasColumnType("integer");

                    b.Property<int>("NewRegistrations")
                        .HasColumnType("integer");

                    b.Property<string>("TopCategory")
                        .HasColumnType("text");

                    b.Property<string>("TopDataSet")
                        .HasColumnType("text");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("integer");

                    b.Property<int>("TotalViews")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PortalStatistics");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 7, 10, 11, 11, 798, DateTimeKind.Utc).AddTicks(3143),
                            Email = "admin@acikveri.gov.tr",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$uQgvUB5b/rSpiw3TKOvfO.E7iFH4EKnyBdIe037AlADNZSbtJgOYu",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserIp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.WebhookLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<double>("ResponseTimeMs")
                        .HasColumnType("double precision");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TriggeredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("WebhookSubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("TriggeredAt");

                    b.HasIndex("WebhookSubscriptionId");

                    b.ToTable("WebhookLogs");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.WebhookSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .HasColumnType("text");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Url");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("DataSetDataSetTag", b =>
                {
                    b.Property<int>("DataSetsId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("DataSetsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DataSetDataSetTag");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.Category", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataQualityReport", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("QualityReports")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSet", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.Category", "Category")
                        .WithMany("DataSets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.User", "CreatedBy")
                        .WithMany("DataSets")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetAccessLog", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("AccessLogs")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetComment", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Comments")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.DataSetComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AcikVeriPortali.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSet");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetDownload", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Downloads")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.User", "User")
                        .WithMany("Downloads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetExport", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Exports")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSet");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetMetadata", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Metadata")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetSchema", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Schema")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetStatistics", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Statistics")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetSubscription", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetVersion", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Versions")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetView", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", "DataSet")
                        .WithMany("Views")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.Notification", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.UserActivity", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.WebhookLog", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.WebhookSubscription", "WebhookSubscription")
                        .WithMany()
                        .HasForeignKey("WebhookSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookSubscription");
                });

            modelBuilder.Entity("DataSetDataSetTag", b =>
                {
                    b.HasOne("AcikVeriPortali.API.Models.DataSet", null)
                        .WithMany()
                        .HasForeignKey("DataSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcikVeriPortali.API.Models.DataSetTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.Category", b =>
                {
                    b.Navigation("DataSets");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSet", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Comments");

                    b.Navigation("Downloads");

                    b.Navigation("Exports");

                    b.Navigation("Metadata");

                    b.Navigation("QualityReports");

                    b.Navigation("Schema");

                    b.Navigation("Statistics");

                    b.Navigation("Subscriptions");

                    b.Navigation("Versions");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.DataSetComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("AcikVeriPortali.API.Models.User", b =>
                {
                    b.Navigation("DataSets");

                    b.Navigation("Downloads");
                });
#pragma warning restore 612, 618
        }
    }
}
